# Generated by Django 3.2.6 on 2021-08-09 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_post_hot_pos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='hot_pos',
            field=models.CharField(blank=True, choices=[('pos1', 'pos1'), ('pos2', 'pos2'), ('pos3', 'pos3'), ('pos4', 'pos4'), ('pos5', 'pos5')], max_length=4, null=True),
        ),
    ]
